Refactor fungible token
FuelLabs/fuel-bridge pull request #12
Opened 2023-07-14 17:05 UTC by Braqzen

Closes #2

2023-07-28 14:07 UTC, luizstacio requested changes

2023-07-28 14:19 UTC, Braqzen commented on packages/fungible-token/bridge-fungible-token/src/data_structures.sw
> +        // TODO: Bug, have to mutate this struct for these values or tests fail
It's a bug caused by memory corruption in Sway.

Teams are looking into this so eventually this will be updated once the fix hits a release.

2023-07-28 14:20 UTC, Braqzen commented on packages/fungible-token/bridge-fungible-token/src/cast.sw
> +// TODO: https://github.com/FuelLabs/sway/issues/4800
Depends, who are the "people" that you're referring to?

This is only meant for us to update the code later. No one else is "meant" to look at this

2023-08-01 15:33 UTC, luizstacio approved these changes

2023-08-01 15:52 UTC, merged