Bridge handshake protocol
FuelLabs/fuel-bridge pull request #82
Opened 2023-10-02 13:26 UTC by DefiCake

This PR adds a handshake protocol that ensures no funds are lost when depositing in the canonical bridge.

2023-10-13 17:50 UTC, K1-R1 requested changes
Looking good, only requested changes to the .sol licences

2023-10-13 17:50 UTC, K1-R1 commented on packages/solidity-contracts/contracts/messaging/gateway/v2/FuelBridgeBaseV2.sol
> +// SPDX-License-Identifier: MIT
```suggestion
// SPDX-License-Identifier: Apache-2.0
```

2023-10-20 08:15 UTC, DefiCake commented
Rebased with main, re-requesting reviews

2023-10-20 17:01 UTC, K1-R1 approved these changes

2023-10-20 17:04 UTC, merged